### ISSUE TITLE
Bug Report: Encounter runner, grunt template, text replacement for health/heath/etc

### ISSUE THREAD

**Issue by jarena3** [massif-press/lancer-data#46] opened 2019-07-14 01:51 UTC
<strong>Submitted At: </strong>7/14/2019 1:51:13
<strong>Item: </strong>Encounter runner, grunt template, text replacement for health/heath/etc
<strong>Incorrect Text: </strong>The grunt only has 1 HP, structure and stress maximum. If it takes heat, it shuts down. If it takes damage, it's destroyed. 
<strong>Correct Text/Ref: </strong>The grunt only has 1 HP, structure and stress maximum. If it takes heat from an external source, it is destroyed. If it takes damage, it's destroyed. 
<strong>Contact Info: </strong>

**Comment by aritsune** [comment] 2019-07-14 16:14
dupe of #45

**Closed as completed by aritsune** 2019-07-14 16:14 UTC
Labels: bug
